### ISSUE TITLE
Spill iframe content out of container

### ISSUE THREAD

**Issue by stvstnfrd** [Mindtoeye/XBlockStattutor#15]
## Issue

Loading an XBlock instance in the LMS renders itself too wide, causing
it to spill out of the containing DIV.
## Reproduction: (in devstack)
- Add a stattutor XBlock to a course via CMS.
- View XBlock in LMS.
- See content overflow.
## Screenshots

![screen shot 2016-07-15 at 13 16 50](https://cloud.githubusercontent.com/assets/7300975/16890713/e4778d7a-4aa5-11e6-91ea-28bc6f3ce686.png)

**Comment by Ringenberg** [comment]
The original StatTutor in OLI was designed with these dimensions and to maintain compatibility between the original and this, the default dimension will not be changed. Now that #16 is fixed, the dimensions can be adjusted to whatever you like, but it is recommended that the width and height not be dropped below the default values as there is content that will become hard for students to interact with if the display is any narrower or shorter.
