### ISSUE TITLE
Ignore "Max Width" and "Max Height"

### ISSUE THREAD

**Issue by stvstnfrd** [Mindtoeye/XBlockStattutor#16]
## Issue

No matter what values are entered in the Studio editor, the iframe is
always rendered with the same, default dimensions.
## Reproduction: (in devstack)
- Add a stattutor XBlock to a course via CMS.
- Click "Edit" for that XBlock.
- Change "Max Height" and/or "Max Width".
- Click save.
- View XBlock in LMS.
- See iframe still displayed at default dimensions.

**Comment by Ringenberg** [comment]
Changing these settings now work, though it is advised not to reduce them below the defaults as the interface was designed to work with those dimensions.
