### ISSUE TITLE
Display component name with gibberish/hex

### ISSUE THREAD

**Issue by stvstnfrd** [Mindtoeye/XBlockStattutor#17]
## Issue

Since no "display name" is ever set for the XBlock, it is always
rendered with a long hex string, instead of a human readable value.
## Reproduction: (in devstack)
- Add a stattutor XBlock to a course via CMS.
- Notice hex in CMS (see screenshot).
- View XBlock in LMS.
- Hover over the unit in the filmstrip navigation.
- Notice hex in LMS.
## Screenshots

![screen shot 2016-07-15 at 16 00 06](https://cloud.githubusercontent.com/assets/7300975/16890742/3be2ecf8-4aa6-11e6-9e7d-ae017009d60c.png)

**Comment by Ringenberg** [comment]
It now displays "StatTutor" instead of the generated id.
